### ISSUE TITLE
Blur

### ISSUE THREAD

**Issue by giga-byt** [dali-lab/tarsier-v2#1]
Don't murder framerate

**Comment by Arkendorf** [comment]
Failed attempts:
1. Creating multiple game objects for every object in the scene and overlaying them with different transparencies. This could potentially work, but looked really bad and ended up getting really messy
2. OnRenderImage shader. LWRP does not support OnRenderImage
3. Downsampling with RenderTextures. No way to redraw the rendertexture to the screen, GUI layer does not exist in VR.
4. Shader on a transparent filter in front of the camera. LWRP does not support grabpass.
5. And probably more I've forgotten.
