### ISSUE TITLE
Allow joystick to move perspective (15 degrees)

### ISSUE THREAD

**Issue by kristiechow** [dali-lab/tarsier-v2#54]

**Comment by Arkendorf** [comment]
Managed to get this working pretty well, will push later when I've got my other stuff working

**Comment by Arkendorf** [comment]
One note: for VRTK_ControllerEvents, the documentation says that Touchpad axes range from 0 to 1, depending on where they are touched (or where the joystick is positioned). You might logically assume then that .5 is the default, neutral position for each axis. This is false. The default position is 0, and, at least for the Quest, the axis can range from -1 to 1, unlike what the documentation claims.
