### ISSUE TITLE
Lobby models

### ISSUE THREAD

**Issue by caxawu** [dali-lab/tarsier-v2#57]
Under construction tape / sign / cones for other animal podiums in the lobby

**Comment by caxawu** [comment]
**Tarsier podium**
![image](https://user-images.githubusercontent.com/39289319/78507106-229a9f80-774c-11ea-857c-c6727320d6b2.png)

**Placeholder Podium**
![image](https://user-images.githubusercontent.com/39289319/78507155-64c3e100-774c-11ea-90a5-c05b23c13a2c.png)

**Lobby view**
![image](https://user-images.githubusercontent.com/39289319/78507172-7efdbf00-774c-11ea-8af1-5fd76fc9b0bc.png)

**Comment by dorothyqu** [comment]
kewt
